[tools]
"asdf:jtakakura/asdf-odin" = "dev-2025-07"

[env]
# How to prepend PATH instead of replacing?
"PATH" = "bin"

[tasks.bootstrap]
run = 'odin build build.odin -file -out:bin/build'

[tasks.release]
depends = ["bootstrap"]
run = './build -release'

[tasks.develop]
depends = ["bootstrap"]
run = './build -develop'

[tasks.test]
depends = ["bootstrap"]
run = './build -test -verbose'

[tasks.check]
run = './build -check'
